<?php
require_once __DIR__.'/includes/bootstrap.php';
$title='Doces do Casal';
$products=db()->query("SELECT p.id,p.nome,p.descricao,p.preco_venda,p.imagem,p.controla_estoque,c.nome categoria,ie.estoque_atual FROM produtos p LEFT JOIN categorias c ON c.id=p.categoria_id LEFT JOIN itens_estoque ie ON ie.produto_id=p.id AND ie.tipo='produto_pronto' AND ie.ativo=1 WHERE p.disponivel=1 ORDER BY p.destaque DESC,p.nome")->fetchAll();
$hero=setting('hero_image','');$casal=setting('foto_casal','');
$tituloHistoria=setting('titulo_historia','Nossa história começou com amor — e ganhou sabor.');
$textoHistoria=setting('texto_historia',"Tudo começou quando nos conhecemos e nos apaixonamos.\n\nCom o tempo, descobri que a Ana tinha um talento especial: ela fazia doces incríveis.\n\nFoi então que decidimos transformar esse amor em um sonho compartilhado e criamos a Doces do Casal.");
$campanhas=db()->query("SELECT id,titulo,subtitulo,imagem,texto_botao,link_botao,data_inicio,data_fim,ordem FROM campanhas WHERE ativo=1 AND (data_inicio IS NULL OR data_inicio<=CURDATE()) AND (data_fim IS NULL OR data_fim>=CURDATE()) ORDER BY ordem,id DESC")->fetchAll();
include __DIR__.'/includes/header.php';
?>
<style>
.hero-admin{padding:80px 0;background:#FFF8F0}.hero-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center}.hero-admin h1{font-family:Georgia,serif;font-size:clamp(48px,5vw,76px);line-height:1;color:#4A2718;margin:0}.hero-admin h1 span{display:block;color:#C98F82}.hero-admin p{font-size:18px;line-height:1.7;color:#765e55}.hero-admin-photo{min-height:560px;border-radius:190px 190px 35px 35px;overflow:hidden;background:#F3DDD4;display:grid;place-items:center;color:#9a7568;text-align:center}.hero-admin-photo img{width:100%;height:100%;object-fit:cover}.campaign-section{padding:80px 0}.campaign-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.campaign-card{position:relative;min-height:400px;border-radius:26px;overflow:hidden;background:#F3DDD4}.campaign-card img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.campaign-card:after{content:"";position:absolute;inset:0;background:linear-gradient(to top,rgba(38,21,15,.7),transparent 65%)}.campaign-content{position:absolute;left:22px;right:22px;bottom:22px;z-index:2;color:white}.campaign-content h3{font-family:Georgia,serif;font-size:28px;margin:0 0 6px}.campaign-content p{margin:0 0 14px}.campaign-link{display:inline-flex;padding:9px 14px;border-radius:999px;background:#FFF8F0;color:#4A2718;font-weight:700}.story-section{padding:90px 0;background:#FFF8F0}.story-grid2{display:grid;grid-template-columns:.9fr 1.1fr;gap:60px;align-items:center}.story-img{width:100%;min-height:520px;object-fit:cover;border-radius:30px 130px 30px 30px;background:#F3DDD4}.story-text h2{font-family:Georgia,serif;font-size:clamp(40px,4vw,60px);color:#4A2718;line-height:1.03;margin:0 0 24px}.story-text p{font-size:17px;line-height:1.8;color:#6e5146}.stock-note{display:block;margin-top:10px;font-size:13px;font-weight:800;color:#2F7D4A}.stock-note.low{color:#B77A50}.stock-note.out{color:#A2392F}.add-btn[disabled]{opacity:.55;cursor:not-allowed;filter:grayscale(.15)}section[id]{scroll-margin-top:150px}@media(max-width:900px){.hero-admin-grid,.story-grid2{grid-template-columns:1fr}.campaign-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.campaign-grid{grid-template-columns:1fr}}
</style>
<main>
<section id="inicio" class="hero-admin"><div class="container hero-admin-grid">
<div><span class="eyebrow">FEITO COM AMOR • FEITO A DOIS</span><h1>Um doce que começou <span>com a gente.</span></h1><p>E agora faz parte dos seus momentos. Doces artesanais preparados com carinho para transformar pequenos momentos em lembranças especiais.</p><div class="hero-actions"><a class="btn primary" href="#cardapio">Quero meu doce</a><a class="btn outline" href="#nossa-historia">Nossa História</a></div></div>
<div class="hero-admin-photo"><?php if($hero):?><img src="<?=e(imagem_otimizada_url($hero))?>" alt="Doces do Casal" fetchpriority="high" decoding="async"><?php else:?>Adicione a foto principal em<br>Admin → Site / Campanhas<?php endif;?></div>
</div></section>

<?php if($campanhas):?><section class="campaign-section"><div class="container"><div class="section-head"><div><span class="eyebrow">MOMENTOS DOCES</span><h2>Campanhas e novidades</h2></div></div><div class="campaign-grid">
<?php foreach($campanhas as $c):?><article class="campaign-card"><img src="<?=e(imagem_otimizada_url($c['imagem']))?>" alt="<?=e($c['titulo'])?>" loading="lazy" decoding="async"><div class="campaign-content"><h3><?=e($c['titulo'])?></h3><?php if($c['subtitulo']):?><p><?=e($c['subtitulo'])?></p><?php endif;?><?php if($c['texto_botao']&&$c['link_botao']):?><a class="campaign-link" href="<?=e($c['link_botao'])?>"><?=e($c['texto_botao'])?></a><?php endif;?></div></article><?php endforeach;?>
</div></div></section><?php endif;?>

<section id="cardapio" class="section"><div class="container"><div class="section-head"><div><h2>Escolha seu favorito</h2><p>Produtos disponíveis para pedido.</p></div></div><div class="products-grid">
<?php foreach($products as $p):?><?php $controla=!empty($p['controla_estoque']);$estoque=$p['estoque_atual']!==null?(float)$p['estoque_atual']:0;$esgotado=$controla&&$estoque<=0;?><article class="product-card"><div class="product-image"><?php if($p['imagem']):?><img src="<?=e(imagem_otimizada_url($p['imagem']))?>" alt="<?=e($p['nome'])?>" loading="lazy" decoding="async"><?php else:?><div class="mini-brownie"></div><?php endif;?></div><div class="product-body"><small class="eyebrow"><?=e($p['categoria']??'Doces do Casal')?></small><h3><?=e($p['nome'])?></h3><p><?=e($p['descricao'])?></p><?php if($controla):?><?php if($esgotado):?><small class="stock-note out">Produto esgotado no momento</small><?php elseif($estoque<=5):?><small class="stock-note low">Últimas <?=(int)$estoque?> unidades</small><?php else:?><small class="stock-note"><?=(int)$estoque?> disponíveis</small><?php endif;?><?php endif;?><div class="product-bottom"><span class="price"><?=money($p['preco_venda'])?></span><button class="add-btn" data-add="<?=$p['id']?>" data-name="<?=e($p['nome'])?>" data-price="<?=$p['preco_venda']?>" data-stock="<?=$controla?(int)$estoque:''?>" <?=$esgotado?'disabled':''?>><?=$esgotado?'Esgotado':'+ Adicionar'?></button></div></div></article><?php endforeach;?>
<?php if(!$products):?><p>Nenhum produto disponível.</p><?php endif;?>
</div></div></section>

<section id="nossa-historia" class="story-section"><div class="container story-grid2">
<div><?php if($casal):?><img class="story-img" src="<?=e(imagem_otimizada_url($casal))?>" alt="Nossa história" loading="lazy" decoding="async"><?php else:?><div class="story-img" style="display:grid;place-items:center;text-align:center;color:#9a7568;padding:30px">Adicione a foto do casal em<br>Admin → Site / Campanhas</div><?php endif;?></div>
<div class="story-text"><span class="eyebrow">NOSSA HISTÓRIA</span><h2><?=e($tituloHistoria)?></h2>
<?php foreach(preg_split('/\R\s*\R/',trim($textoHistoria)) as $p):?><?php if(trim($p)!==''):?><p><?=nl2br(e(trim($p)))?></p><?php endif;?><?php endforeach;?>
</div></div></section>

<section id="fidelidade" class="section"><div class="container loyalty-grid"><div><span class="eyebrow">MEU CASAL</span><h2>Seu cartão fidelidade digital</h2><p>Crie sua conta, acompanhe seus pedidos e acumule pontos.</p></div><div class="card"><?php if(current_user()):?><h3>Olá, <?=e(current_user()['nome'])?></h3><a class="btn primary full" href="/cliente/">Abrir minha conta</a><?php else:?><h3>Entre no Meu Casal</h3><p>Pedidos, pontos e endereços em um só lugar.</p><a class="btn primary full" href="/auth/login.php">Entrar</a><a class="btn outline full" style="margin-top:10px" href="/auth/register.php">Criar conta</a><?php endif;?></div></div></section>
</main>
<aside class="drawer" id="cartDrawer"><div class="drawer-head"><h3>Carrinho</h3><button class="icon-btn" id="closeCart">×</button></div><div class="drawer-body" id="cartItems"></div><div class="drawer-footer"><div class="summary-row"><span>Total</span><strong id="cartTotal">R$ 0,00</strong></div><button class="btn primary full" id="checkoutBtn">Finalizar pedido</button></div></aside><div class="backdrop" id="backdrop"></div>
<?php include __DIR__.'/includes/footer.php'; ?>
